# Generated by Django 3.0.3 on 2020-02-25 18:42

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='started',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='move',
            name='time_made',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2020, 2, 25, 18, 42, 16, 431553, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
