# Generated by Django 3.0.3 on 2020-02-27 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='first_move',
        ),
        migrations.RemoveField(
            model_name='game',
            name='last_move',
        ),
        migrations.DeleteModel(
            name='Move',
        ),
    ]
