# Generated by Django 3.0.3 on 2020-03-11 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='first_move',
        ),
        migrations.RemoveField(
            model_name='game',
            name='last_move',
        ),
        migrations.AddField(
            model_name='game',
            name='moves',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='game',
            name='status',
            field=models.CharField(choices=[('o', 'open'), ('d', 'draw'), ('1', 'white wins'), ('0', 'black wins')], default='o', max_length=1),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Move',
        ),
    ]
