# Generated by Django 3.0.3 on 2020-03-05 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_auto_20200227_1239'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='moves',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
