# Generated by Django 3.0.3 on 2020-02-25 22:50

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_auto_20200225_1342'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='p1_last',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 25, 22, 50, 24, 8382, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='game',
            name='p2_last',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 25, 22, 50, 30, 89508, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
