# Generated by Django 3.0.3 on 2020-03-05 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_game_moves'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='status',
            field=models.CharField(choices=[('o', 'open'), ('d', 'draw'), ('1', 'white wins'), ('0', 'black wins')], default='o', max_length=1),
            preserve_default=False,
        ),
    ]
