# Generated by Django 3.0.3 on 2020-02-25 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_auto_20200225_1750'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='p1_last',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='p2_last',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
