# Generated by Django 3.0.3 on 2020-02-21 20:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Move',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notation', models.CharField(max_length=10)),
                ('next_move', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prev_move', to='chess.Move')),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=24, unique=True)),
                ('fen', models.CharField(max_length=100)),
                ('move_index', models.IntegerField()),
                ('first_move', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='first', to='chess.Move')),
                ('last_move', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='last', to='chess.Move')),
                ('p1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='p1_games', to=settings.AUTH_USER_MODEL)),
                ('p2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='p2_games', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
