# Generated by Django 3.0.3 on 2020-02-22 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chess', '0002_auto_20200221_1533'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='move',
            name='notation',
        ),
        migrations.AddField(
            model_name='move',
            name='source',
            field=models.CharField(default='', max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='move',
            name='target',
            field=models.CharField(default='', max_length=2),
            preserve_default=False,
        ),
    ]
